### ISSUE TITLE
properties hideForgotPasswordButton and hideSignUpButton not defined

### ISSUE THREAD

**Issue by sehmim2** [NearHuscarl/flutter_login#158] opened 2021-04-16 20:18 UTC
**Describe the bug**
Proper not found  on version 1.1.0

Here is how to reproduce the problem on a widget

`  Widget build(BuildContext context) {
    return FlutterLogin(
      title: 'ByDesign ReSkin',
      onLogin: _loginUser,
      onSignup: _registerUser,
      hideSignUpButton: false,
      hideForgotPasswordButton: false,
      onSubmitAnimationCompleted: () {
        Navigator.of(context).pushReplacement(
          MaterialPageRoute(
            builder: (context) => DashboardPage(title: "Dashboard"),
          )
        );
      },
      onRecoverPassword: (_)=> null
    );
  }`

![Screen Shot 2021-04-16 at 4 17 56 PM](https://user-images.githubusercontent.com/52256318/115079528-4f40d580-9ecf-11eb-95b0-2eca10b95714.png)

**Comment by surister** [comment] 2021-04-24 18:51
Works alright in 1.1.0
Cannot reproduce the bug, are you sure you are using the latest?
![image](https://user-images.githubusercontent.com/37985796/115969718-ac2b3400-a53e-11eb-8ed1-6ba55a31729c.png)

**Comment by juliansteenbakker** [comment] 2021-04-30 07:38
This seems like a caching issue. Try `flutter clean` and `flutter pub get` please. I am closing this for now.

**Closed by juliansteenbakker** 2021-04-30 07:38 UTC
Labels: bug
