### ISSUE TITLE
After clicking on show password, the app no longer responds to mouse events

### ISSUE THREAD

**Issue by oysterpack** [NearHuscarl/flutter_login#189] opened 2021-06-17 16:11 UTC
**Describe the bug**
After clicking on show password icon, the password is revealed, but the mouse events stop working, i.e., the app no longer responds to mouse events. The following error continuously happens:

```
Error: Assertion failed: /flutter/packages/flutter/lib/src/rendering/mouse_tracker.dart:201:12
!_debugDuringDeviceUpdate
is not true
    at Object.throw_ [as throw] (http://localhost:43965/dart_sdk.js:5041:11)
    at Object.assertFailed (http://localhost:43965/dart_sdk.js:4980:15)
    at mouse_tracker.MouseTracker.new.[_deviceUpdatePhase] (http://localhost:43965/packages/flutter/src/rendering/layer.dart.lib.js:4665:50)
    at http://localhost:43965/packages/flutter/src/rendering/layer.dart.lib.js:4721:33
    at mouse_tracker.MouseTracker.new.[_monitorMouseConnection] (http://localhost:43965/packages/flutter/src/rendering/layer.dart.lib.js:4661:7)
    at mouse_tracker.MouseTracker.new.updateWithEvent (http://localhost:43965/packages/flutter/src/rendering/layer.dart.lib.js:4720:36)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:43965/packages/flutter/src/rendering/layer.dart.lib.js:5016:46)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerEventImmediately] (http://localhost:43965/packages/flutter/src/gestures/binding.dart.lib.js:321:14)
    at binding$5.WidgetsFlutterBinding.new.handlePointerEvent (http://localhost:43965/packages/flutter/src/gestures/binding.dart.lib.js:295:43)
    at binding$5.WidgetsFlutterBinding.new.[_flushPointerEventQueue] (http://localhost:43965/packages/flutter/src/gestures/binding.dart.lib.js:285:14)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerDataPacket] (http://localhost:43965/packages/flutter/src/gestures/binding.dart.lib.js:276:54)
    at Object.invoke1 (http://localhost:43965/dart_sdk.js:175635:7)
    at _engine.EnginePlatformDispatcher.__.invokeOnPointerDataPacket (http://localhost:43965/dart_sdk.js:157073:15)
    at _engine.PointerBinding.__.[_onPointerData] (http://localhost:43965/dart_sdk.js:157712:49)
    at http://localhost:43965/dart_sdk.js:158119:26
    at http://localhost:43965/dart_sdk.js:158086:16
    at http://localhost:43965/dart_sdk.js:157805:11
```

**To Reproduce**
The issue can be reproduced easily when running the **example** project as a webapp, i.e., via `flutter run -d chrome`

**Expected behavior**
I should be able to hide the password again when clicking on the password field's "show" icon again.

**Information (please complete the following information):**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.2, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.1)
[✓] VS Code (version 1.56.2)
[✓] Connected device (1 available)

**Additional context**

**Comment by siman302** [comment] 2021-06-17 23:18
i face the same issue on the window

`[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: 'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 201 pos 12: '!_debugDuringDeviceUpdate': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      MouseTracker._deviceUpdatePhase
package:flutter/…/rendering/mouse_tracker.dart:201
#3      MouseTracker.updateWithEvent.<anonymous closure>
package:flutter/…/rendering/mouse_tracker.dart:309
#4      MouseTracker._monitorMouseConnection
package:flutter/…/rendering/mouse_tracker.dart:190
#5      MouseTracker.updateWithEvent
package:flutter/…/rendering/mouse_tracker.dart:308
#6      RendererBinding.dispatchEvent
package:flutter/…/rendering/binding.dart:285
#7      GestureBinding._handlePointerEventImmediately
package:flutter/…/gestures/binding.dart:374
#8      GestureBinding.handlePointerEvent
package:flutter/…/gestures/binding.dart:338
#9      GestureBinding._flushPointerEventQueue
package:flutter/…/gestures/binding.dart:296
#10     GestureBinding._handlePointerDataPacket
package:flutter/…/gestures/binding.dart:279
#11     _rootRunUnary (dart:async/zone.dart:1370:13)
#12     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#13     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#14     _invoke1 (dart:ui/hooks.dart:182:10)
#15     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:282:7)
#16     _dispatchPointerDataPacket (dart:ui/hooks.dart:96:31)

════════ Exception caught by scheduler library ═════════════════════════════════
'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 201 pos 12: '!_debugDuringDeviceUpdate': is not true.
════════════════════════════════════════════════════════════════════════════════
`

**Comment by komangnopha** [comment] 2021-07-15 14:36
same here.. pls fix this bug, thanks.

**Comment by cbanaspk** [comment] 2021-08-06 18:32
Facing the same issue

**Comment by juliansteenbakker** [comment] 2021-08-17 07:04
This seems like an issue with the animatedCrossFade of the AnimatedTextFormField object. Settings the duration of the animation fixes the issue. Need some more debugging on how we can fix this while retaining the animation.

**Comment by juliansteenbakker** [comment] 2021-08-17 07:23
It seems like the problem is caused not only directly by the `animatedCrossFade` widget. When isolating it, it doesn't seem to cause any issues. However when we isolate `AnimatedTextFormField` it does give the error. Also, when setting the duration to zero, it will give another error.

**Comment by jeffreyliu8** [comment] 2021-09-02 05:30
face same issue on chrome browser.

**Comment by BitPampers** [comment] 2021-09-30 23:23
The issue is still there (as of 2.2.1). 
Maybe just add an option to hide this "show password" button at least?
e.g. `disableShowPasswordButton` to set it to true when the platform is web.
Some users may be really unhappy after entering email and a long password, just clicking eye to double check everything and being stuck. Having to reload the page and repeat everything. Maybe even leaving frustrated 🤬
We don't want that.

**Comment by juliansteenbakker** [comment] 2021-11-13 21:22
This is a flutter issue, which has already been resolved in the dev and beta channels.

**Closed by juliansteenbakker** 2021-11-13 21:22 UTC
Labels: bug, help wanted
