### ISSUE TITLE
How to remove buttons and fields? 

### ISSUE THREAD

**Issue by danieramiz** [NearHuscarl/flutter_login#47] opened 2020-03-06 03:42 UTC
I want to use the plugin but, I don't really need the forgot password or the signup stuff 

I sow the AuthCard class has some methods to build the buttons. Is there a way to remove those? 

Thanks,

**Comment by joaquimorg** [comment] 2020-03-17 16:02
Yes you can do this :
messages: LoginMessages(
signupButton: '',
forgotPasswordButton: '',
)

**Comment by dhs9004** [comment] 2020-03-30 21:13
> Yes you can do this :
> messages: LoginMessages(
> signupButton: '',
> forgotPasswordButton: '',
> )

but it still will go to the forgotPasswordButton page

**Comment by evertonAlvaro** [comment] 2020-06-03 06:30
Hello, you find this in my fork.
hideButtonForgotPassword and hideButtonSignUp Propertys
https://github.com/evertonAlvaro/flutter_login#reference

**Comment by Ramax11** [comment] 2020-12-16 06:34
@evertonAlvaro How to use your code.. with Flutter login lib..?

**Comment by evertonAlvaro** [comment] 2020-12-17 04:54
> @evertonAlvaro How to use your code.. with Flutter login lib..?
@Ramax11
```
dependencies:
   flutter_login: 
       git: 
         url: https://github.com/evertonAlvaro/flutter_login.git
         ref: master
```

**Comment by juliansteenbakker** [comment] 2021-03-16 10:44
Duplicate of #19

**Closed by juliansteenbakker** 2021-03-16 10:44 UTC
Labels: bug
