### ISSUE TITLE
Can I request the possibility to disable the "Register" Button

### ISSUE THREAD

**Issue by von-maurus** [NearHuscarl/flutter_login#72] opened 2020-07-28 22:27 UTC
Hi!, first, thank you so much for your Widget, it's really cool specialy the animations. I wanted to request adding the possibility to change the state of the elements in the widget. Eg: a boolean value to whether or not showing the buttons, Sign up & Sign In. 

Also, It would be cool adding some more labels or buttons to it. (like google+ or FB sign In).

![image](https://user-images.githubusercontent.com/9019172/88728137-0b1e6280-d0ff-11ea-8c8d-3ae44c8abb7a.png)

**Comment by justinemailone** [comment] 2020-08-19 19:18
I also need to disable the register button. I noticed the code had the properties `// hideButtonForgotPassword: true,
      // hideButtonSignUp: true,` commented out and they are not implemented.

**Comment by mehmetyilmaz001** [comment] 2020-08-28 18:16
I also need this feature.

**Comment by kahlil29** [comment] 2020-09-05 17:12
I too need to hide or disable to register button. 
If not, is there a way to do another action when the register button is pressed? E.g. a popup/dialog with some text.

**Comment by kahlil29** [comment] 2020-09-05 17:50
I found a workaround/solution at #63

**Comment by juliansteenbakker** [comment] 2021-03-16 10:40
Duplicate of #19

**Closed by juliansteenbakker** 2021-03-16 10:40 UTC
Labels: bug
