### ISSUE TITLE
WEB : Login Text not center

### ISSUE THREAD

**Issue by QuentinSc** [NearHuscarl/flutter_login#28] opened 2020-01-07 16:06 UTC
Hello,

Flutter : 1.12.13+6
Env : Chrome

![image](https://user-images.githubusercontent.com/16439299/71909281-f92f9f00-316f-11ea-90f9-a6a0c2fa82ce.png)

**Comment by doc-rj** [comment] 2020-01-07 16:09
@QuentinSc This looks like a duplicate of #7 - I think there is a workaround in there.

**Comment by QuentinSc** [comment] 2020-01-07 17:08
Oups you're right sorry. But no real workaround :(

**Comment by NearHuscarl** [comment] 2020-01-16 17:31
Close as duplicated to #7

**Closed by NearHuscarl** 2020-01-16 17:31 UTC
