### ISSUE TITLE
seeing password results in screen freeze and error in browser

### ISSUE THREAD

**Issue by nyck33** [NearHuscarl/flutter_login#286] opened 2021-11-21 23:55 UTC
When I click the eye to see my password in Chrome, the browser freezes (can't push login button) and I get
```
Error: Assertion failed: file:///home/nobu/snap/flutter/common/flutter/packages/flutter/lib/src/rendering/mouse_tracker.dart:201:12
!_debugDuringDeviceUpdate
is not true
    at Object.throw_ [as throw] (http://localhost:42049/dart_sdk.js:5061:11)
    at Object.assertFailed (http://localhost:42049/dart_sdk.js:4986:15)
    at mouse_tracker.MouseTracker.new.[_deviceUpdatePhase] (http://localhost:42049/packages/flutter/src/rendering/layer.dart.lib.js:4779:50)
    at http://localhost:42049/packages/flutter/src/rendering/layer.dart.lib.js:4833:33
    at mouse_tracker.MouseTracker.new.[_monitorMouseConnection] (http://localhost:42049/packages/flutter/src/rendering/layer.dart.lib.js:4775:7)
    at mouse_tracker.MouseTracker.new.updateWithEvent (http://localhost:42049/packages/flutter/src/rendering/layer.dart.lib.js:4832:36)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:42049/packages/flutter/src/rendering/layer.dart.lib.js:5117:44)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerEventImmediately] (http://localhost:42049/packages/flutter/src/gestures/binding.dart.lib.js:321:14)
    at binding$5.WidgetsFlutterBinding.new.handlePointerEvent (http://localhost:42049/packages/flutter/src/gestures/binding.dart.lib.js:295:43)
    at binding$5.WidgetsFlutterBinding.new.[_flushPointerEventQueue] (http://localhost:42049/packages/flutter/src/gestures/binding.dart.lib.js:285:14)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerDataPacket] (http://localhost:42049/packages/flutter/src/gestures/binding.dart.lib.js:276:54)
    at Object.invoke1 (http://localhost:42049/dart_sdk.js:179667:7)
    at _engine.EnginePlatformDispatcher.__.invokeOnPointerDataPacket (http://localhost:42049/dart_sdk.js:160119:15)
    at _engine.PointerBinding.__.[_onPointerData] (http://localhost:42049/dart_sdk.js:160965:49)
    at http://localhost:42049/dart_sdk.js:161373:26
    at http://localhost:42049/dart_sdk.js:161340:16
    at loggedHandler (http://localhost:42049/dart_sdk.js:161058:11)
Error: Assertion failed: file:///home/nobu/snap/flutter/common/flutter/packages/flutter/lib/src/rendering/mouse_tracker.dart:201:12
!_debugDuringDeviceUpdate
is not true
    at Object.throw_ [as throw] (http://localhost:42049/dart_sdk.js:5061:11)
    at Object.assertFailed (http://localhost:42049/dart_sdk.js:4986:15)
    at mouse_tracker.MouseTracker.new.[_deviceUpdatePhase] (http://localhost:42049/packages/flutter/src/rendering/layer.dart.lib.js:4779:50)
    at http://localhost:42049/packages/flutter/src/rendering/layer.dart.lib.js:4833:33
    at mouse_tracker.MouseTracker.new.[_monitorMouseConnection] (http://localhost:42049/packages/flutter/src/rendering/layer.dart.lib.js:4775:7)
    at mouse_tracker.MouseTracker.new.updateWithEvent (http://localhost:42049/packages/flutter/src/rendering/layer.dart.lib.js:4832:36)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:42049/packages/flutter/src/rendering/layer.dart.lib.js:5117:44)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerEventImmediately] (http://localhost:42049/packages/flutter/src/gestures/binding.dart.lib.js:321:14)
    at binding$5.WidgetsFlutterBinding.new.handlePointerEvent (http://localhost:42049/packages/flutter/src/gestures/binding.dart.lib.js:295:43)
    at binding$5.WidgetsFlutterBinding.new.[_flushPointerEventQueue] (http://localhost:42049/packages/flutter/src/gestures/binding.dart.lib.js:285:14)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerDataPacket] (http://localhost:42049/packages/flutter/src/gestures/binding.dart.lib.js:276:54)
    at Object.invoke1 (http://localhost:42049/dart_sdk.js:179667:7)
    at _engine.EnginePlatformDispatcher.__.invokeOnPointerDataPacket (http://localhost:42049/dart_sdk.js:160119:15)
    at _engine.PointerBinding.__.[_onPointerData] (http://localhost:42049/dart_sdk.js:160965:49)
    at http://localhost:42049/dart_sdk.js:161373:26
    at http://localhost:42049/dart_sdk.js:161340:16
    at loggedHandler (http://localhost:42049/dart_sdk.js:161058:11)
Error: Assertion failed: file:///home/nobu/snap/flutter/common/flutter/packages/flutter/lib/src/rendering/mouse_tracker.dart:201:12
!_debugDuringDeviceUpdate
is not true
    at Object.throw_ [as throw] (http://localhost:42049/dart_sdk.js:5061:11)
    at Object.assertFailed (http://localhost:42049/dart_sdk.js:4986:15)
    at mouse_tracker.MouseTracker.new.[_deviceUpdatePhase] (http://localhost:42049/packages/flutter/src/rendering/layer.dart.lib.js:4779:50)
    at http://localhost:42049/packages/flutter/src/rendering/layer.dart.lib.js:4833:33
    at mouse_tracker.MouseTracker.new.[_monitorMouseConnection] (http://localhost:42049/packages/flutter/src/rendering/layer.dart.lib.js:4775:7)
    at mouse_tracker.MouseTracker.new.updateWithEvent (http://localhost:42049/packages/flutter/src/rendering/layer.dart.lib.js:4832:36)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:42049/packages/flutter/src/rendering/layer.dart.lib.js:5117:44)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerEventImmediately] (http://localhost:42049/packages/flutter/src/gestures/binding.dart.lib.js:321:14)
    at binding$5.WidgetsFlutterBinding.new.handlePointerEvent (http://localhost:42049/packages/flutter/src/gestures/binding.dart.lib.js:295:43)
    at binding$5.WidgetsFlutterBinding.new.[_flushPointerEventQueue] (http://localhost:42049/packages/flutter/src/gestures/binding.dart.lib.js:285:14)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerDataPacket] (http://localhost:42049/packages/flutter/src/gestures/binding.dart.lib.js:276:54)
    at Object.invoke1 (http://localhost:42049/dart_sdk.js:179667:7)
    at _engine.EnginePlatformDispatcher.__.invokeOnPointerDataPacket (http://localhost:42049/dart_sdk.js:160119:15)
    at _engine.PointerBinding.__.[_onPointerData] (http://localhost:42049/dart_sdk.js:160965:49)
    at http://localhost:42049/dart_sdk.js:161373:26
    at http://localhost:42049/dart_sdk.js:161340:16
    at loggedHandler (http://localhost:42049/dart_sdk.js:161058:11)
Error: Assertion failed: file:///home/nobu/snap/flutter/common/flutter/packages/flutter/lib/src/rendering/mouse_tracker.dart:201:12
!_debugDuringDeviceUpdate
```

**Comment by rachonzedev** [comment] 2021-12-01 08:39
Same error in web mode with chrome browser...

**Comment by ilic5000** [comment] 2021-12-07 15:09
Same problem here.

Any updates from the maintainers? Will it be fixed soon?

**Comment by juliansteenbakker** [comment] 2021-12-07 15:10
Please see https://github.com/NearHuscarl/flutter_login/issues/189#issuecomment-968137967

Closing as duplicate of #189

**Closed by juliansteenbakker** 2021-12-07 15:10 UTC
Labels: bug
