### ISSUE TITLE
i need custom design how to remove unnecessary btns 

### ISSUE THREAD

**Issue by foxmedo** [NearHuscarl/flutter_login#63] opened 2020-05-23 13:02 UTC
Hello i need to make a custom design 

i need to remove the title, the Register btn and password forget 

the only think i need is the login for to work with firebase and how to do the logout 

waiting for your suggestions

**Comment by evertonAlvaro** [comment] 2020-06-03 06:18
Hi @foxmedo, you find this in my fork.
https://github.com/evertonAlvaro/flutter_login

**Comment by TafadzwaD** [comment] 2020-07-15 01:11
@evertonAlvaro How can i show a custom snackbar message after clicking signup Button. A success snackbar

**Comment by kahlil29** [comment] 2020-09-05 17:41
Hey @evertonAlvaro 
Thanks for linking to your fork with the customization options. 
How to use your fork of the plugin instead of the official/original `flutter_login` plugin?

**Comment by kahlil29** [comment] 2020-09-05 17:50
Alright I figured it out using [this answer](https://stackoverflow.com/questions/51238420/how-to-use-local-flutter-package-in-another-flutter-application) on StackOverflow 
Thanks @evertonAlvaro, the options you've added work flawlessly and should really be merged in to the official version! :+1:

**Comment by evertonAlvaro** [comment] 2020-09-06 02:59
> Hey @evertonAlvaro
> Thanks for linking to your fork with the customization options.
> How to use your fork of the plugin instead of the official/original `flutter_login` plugin?

Hi @kahlil29 , I am very happy to help, if you have any problems or ideas, I am available.
flutter_login: 
    git: 
      url: https://github.com/evertonAlvaro/flutter_login.git
      ref: master

**Comment by winds1983** [comment] 2020-12-05 10:39
> Hi @foxmedo, you find this in my fork.
> https://github.com/evertonAlvaro/flutter_login

I also need this, thanks.

**Comment by juliansteenbakker** [comment] 2021-03-16 10:43
Duplicate of #19. Thanks for your contribution @evertonAlvaro, i will check if some functions can be merged.

**Closed by juliansteenbakker** 2021-03-16 10:43 UTC
